### ISSUE TITLE
(internal) UDB + ACID

### ISSUE THREAD

**Issue by Grz3s** [unified-db/Database#112]
Hi all...
Working on WoTLK (TBC also) ... many Times i have to use EAI...to be able to fix stuff...
Often you may see fixes for quests/events/etc... that half is done using DBScripts and another half using EAI...
As example we can take npc =A.. that with dbscript casting spell on npc =B.
Npc=B will use EAI 'onspell HIT" to do smth with npc=A ...etc....
So ... we have to create 2 scripts:
- 1 for DB
- 1 for ACID
 
I can push DB path ... and then i have to ask @xfurry  or @X-Savior to add it into ACID... I'm not going to lie on this... i dont like it at all.

Also it creates 2 questions:
1st:
AciD should be ok for all DB providers... so what for example YTBD devs will do ... if ill add like above one.. script. - they will be forced to do the same? (maybe they have a diff method to do it?)
2nd.. im sure ... that pll like @xfurry .. have enough stuff to do, not only be asked so often to add this , that etc...
I tied ... to speak about this issue few Times already ... but ppl wasnt interested.

So: To solve this... I'm planing to "INCLUDE" whole ACID into UDB.... 
and work simmilar like ClassicDB do:
look here - https://github.com/classicdb/database/commit/2e23887b662183ed0b0aceff5d0b2b7747ad3c8f
- first it will save mine and others time ... with adding stuff
- it will keep DB unique - and will not force other DB providers to use the same methods...
- im sure if any update will come on ACID .. i can add it .. quick enough to keep up with 'em

Anyway: 
Reason why im writing all this here ... is i would like to hear what you all think about it..
Is this a good idea?
I hope this time ppl will be more intersted... 
and lets say i'll keep this post open till end of September.
Thank you for any feedback.

**Comment by Tauriella** [comment]
Hi
In my opinion the correct is gone:
ACID and UDB smelt in on Project like SD2 and Cmangos  (God be thanks)
It has the advantage that less Bugs in the Scripts and not 100 X Git Cheks :)

**Comment by xfurry** [comment]
In my opinion, I think it's good to merge ACID and DB under the same roof.
We just need to be sure that all DB providers will agree to do this for each client version.
Poke @cala  for classic and @evil-at-wow  for TBC.

Also, keep in mind that once we do this, someone still needs to keep the ACID scripts in sync between the various version.

And we should not forget that @X-Savior needs to agree with this as well.

**Comment by cala** [comment]
Hi everyone,

I also think that the current workflow needs to be changed. I'm also in favor of bringing ACID and DB projects under the same roof (ultimately, all DB projects under the same roof would be nice).
This would ease and quicken development, in my opinion. But we should also avoid having current project leaders to feel deprieved of their project/work by feeling "what was yours is now ours, fame included".
Thus, we must be careful in doing such a merge to ensure to keep the same quality of work while respecting everyone.

> So: To solve this... I'm planing to "INCLUDE" whole ACID into UDB....
and work simmilar like ClassicDB do

To clarify, including ACID in Classic DB requires that we do a release (*i.e.* a full DB dump related to a milestone) due to different update structure. So, everytime we need to update the AI scripts for a quest or whatever, we also do a PR to ACID. That way, we are always in sync with ACID without having to do a DB release.
But I don't see that as an "include" or "repack" : if Classic DB users want to have ACID installed at the same time than Classic DB, ACID will always be on top of the DB changes.

> And we should not forget that @X-Savior needs to agree with this as well. 

I totally agree and I'd like to point out that in my experience, @X-Savior does not reply to "poke" (his GitHub account is not set that way), so it would be better to catch him on IRC and point him to here. :wink: I don't want him to feel left out.

**Comment by xfurry** [comment]
> I totally agree and I'd like to point out that in my experience, @X-Savior does not reply to "poke" (his GitHub account is not set that way), so it would be better to catch him on IRC and point him to here.  I don't want him to feel left out.

I already did that. He was fine with this, but his only concern was that DB devs don't follow the proper development rules for Acid.
For example, Classic DB does that by creating a separate file with update statements.

I think that Acid file integrity should be kept. That means that whatever we update, we update directly in the file, and not by separate update statements. Same like we do for SD2 update.

**Comment by cala** [comment]
> I think that Acid file integrity should be kept. That means that whatever we update, we update directly in the file, and not by separate update statements. Same like we do for SD2 update.

We already discussed this and I agree. ACID file integrity is kept since PR are **always** made. Separate update files are only used to avoid having to perform a fresh complete install everytime we update a value or a line.
This is similar to what is done with SD2 : there are always updates files (archived at each milestone) and a full SD2 file update. I don't see where the concern is. The only "real" issue I could see is that there a small time lapse were DB and ACID might be out of sync because they are two separate projects. But this will no longer be the case if we merge them under the same roof. :smile:

**Comment by cyberium** [comment]
I intentionaly let this discution between you DB devs. You are more concerned than me.
I just want to point out why this merge can make things better.

- First of all, make DB installation easier for all users (including devs).
- Make change to ACID easier for "DB devs content provider".
- Make ACID more visible for some users that dont know what is it.
- Create more activity in repos.

I was 100% for "all integrated" solution. But actualy we are facing some difficulties.
- Different team working in different way.
- Db update history will be less clear.
- ACID will be less standard over the time bettween each DB provider or core.

The main problem is the first point.
So, finaly i realy think the best solution is:
- Open an ACID repository for each core in cmangos organization.
- Provide access to all db team.
- Define a way to update it clearly in a wiki page.
- Provide a script for easy installation.

The script installation will be soon (i mean a couple of months) be integrated in server code itself as a db wizard. So where is ACID repos and when/where to install/update it will be automaticaly handled. The only important thing is to keep a stable access on it for everyone.

**Comment by xfurry** [comment]
> We already discussed this and I agree. ACID file integrity is kept since PR are always made. Separate update files are only used to avoid having to perform a fresh complete install everytime we update a value or a line.

Ok. It seems that XS wasn't updated with this. He was the one who complained, not me.
I think that keeping separate update files for ACID it's fine, as long as the main file contains everything at any point in time.

> This is similar to what is done with SD2 : there are always updates files (archived at each milestone) and a full SD2 file update.

SD2 will no longer provide individual update files. It will follow the same concept as ACID - one big file.
If DB providers want to add a separate update file, then I have nothing against it.

**Comment by cala** [comment]
No worries, I'm sure we will find a way to have this to work smoothly and nicely.
So, to summarize: I agree that it would be better to have somehow ACID and DB under the same roof. :smile:

**Comment by evil-at-wow** [comment]
Contrary to what @xfurry suggests, I'm not actively developing a TBC database at the moment. I've done some work for TBC-DB in the past - and still do every now and then - but @X-Savior deserves most of the credit.

That said, I can see some benefits when ACID and the DB are brought together. But I also believe that we should keep all ACID versions in sync, otherwise it's going to be a mess soon. I'm not sure if both requirements can be met though, because moving ACID to the DB repositories is going to spread the versions, and keeping them together like it is now is somewhat less efficient for the DB teams.

@cyberium  I don't really see why we should create new repositories for ACID. We have separate repositories already, so just give the right people access to them?

**Comment by xfurry** [comment]
> But I also believe that we should keep all ACID versions in sync, otherwise it's going to be a mess soon. I'm not sure if both requirements can be met though, because moving ACID to the DB repositories is going to spread the versions, and keeping them together like it is now is somewhat less efficient for the DB teams.

It depends on the approach. This already happens for SD2, and as you can see the versions are very out of sync atm. I can't tell if this is good or bad.

**Comment by cyberium** [comment]
>@cyberium I don't really see why we should create new repositories for ACID. We have separate repositories already, so just give the right people access to them?

yes mostly the main actual issue.

**Comment by Grz3s** [comment]
thank you all ... for all comments.
I see now how important is for most to keep ACID as 1 big file.
Also I understand sentiment to X-Saviors work...
 But truth is... 
- I can't see any life in ACID anymore... (99% of updates comming from DB devs)
- about.. keping all versions sync... (good example can be .. me and Cala.. we both trying to keep classic and wotlk sync as much as it possible)
I was hoping that X-S will join here... but i understand ppl private life.

**Comment by xfurry** [comment]
I think that a good start would be if @Grz3s and @cala would be granted commit access to the Acid repos.
This will address most of the points that we discussed here, while we still debate on the future of the proposed integration.

**Comment by Muehe** [comment]
I'd really like to see an organization with a centralised issue tracker for the DBs, like there is for the cores. Would make following everything much easier, especially for new users and people focusing on one version. Right now you'd have to watch like 15 repositories (cmangos core and issues, 4 x SD2, 4x ACID, 5 x DBs) to get notified of all the things happening. Identifying if issues apply to more than one version or even finding the right place for bug reports is a nightmare like this.

**Comment by cala** [comment]
> I think that a good start would be if @Grz3s and @cala would be granted commit access to the Acid repos.

This would indeed be really useful, especially in order to keep ACID and DB projects in sync. :+1:

**Comment by Grz3s** [comment]
it looks like that with 2016 this is not "active" anymore
thanks to all who took part of this.

**Comment by cala** [comment]
Happy new year and best wishes to you @Grz3s and everyone here! :balloon: :christmas_tree: 

Could you please explain why you closed this? Aside from a recent burst of activity in the ACID-TBC repository alone, I don't this any of the issues discussed here being addressed with the coming of 2016, especially since my last reply.
Did I miss something?

**Comment by Grz3s** [comment]
Hi @cala ... Happy 2016. :+1: 
in first post i said:
```quote
(...)and lets say i'll keep this post open till end of September.(...)
```
I kept it longer (and of 2015)
Also you can see my prev. comment https://github.com/unified-db/Database/issues/112#issuecomment-143480336 ... I gave up doing any changes ...because... ppl didnt like it ...
..AND.. then @xfurry came with good proposition...  to give me and you rights to keep this alive.
Believe it or not .. I thought X-Sav.. gave You rights for classic like I was given them.
Hmm... sory that i didnt even look :/

Now it look like ...i wanted smth (i recived it) and didnt care about other ppl :/
I'm sory...

BTW:
I had no idea that smth goin on on ACID_TBC ...
So.. ppl woried that with my prev. concept.. projects wont be synch anymore.... but it looks like it happens already :)

**Comment by cala** [comment]
> in first post i said:
```
(...)and lets say i'll keep this post open till end of September.(...)
```

Sorry, I missed that part, you are right. My mistake. :)

> Believe it or not .. I thought X-Sav.. gave You rights for classic like I was given them.
Hmm... sory that i didnt even look :/

I'm glad you got push rights to ACID repo. This is a good thing for UBD and for the WotLK development.

There is probably a good reason for which I did not get push rights myself. Or maybe, this means that none really cares with (ACID) Classic development anymore.

> I had no idea that smth goin on on ACID_TBC ...
So.. ppl woried that with my prev. concept.. projects wont be synch anymore.... but it looks like it happens already :)

I guess X-Savior will sync WotLK and Classic acids once he's finished all the updates on the TBC one. At least I hope so.

Please, feel free to close this issue if you like it because this is UDB repository here and the UDB part of the issue seems to be partially covered. :)

**Comment by Grz3s** [comment]
I hope you'll get rights for ACID-Classic. (you should).
