### ISSUE TITLE
[Wotlk] Spell: Charge [#11578]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#139]
When using the warrior's charge ability, you will end-up 1-2 yards to far away for you to be able to attack the target.

**Comment by Ulduar** [comment]
Core side.

**Comment by Grz3s** [comment]
pls report core issues here:
https://github.com/cmangos/issues/issues

**Comment by Argonn** [comment]
Is there any 'clear' explanation where to report what kind of issue. Because in some cases i think its core, it ends being DB and vice-versa.

**Comment by Grz3s** [comment]
in short way:

BD issues:
Everything related to world:
- spawns, waypoints, scripts, events, quests, links, toot (but if smth is missing or smth shouldnt be droped at all)

Acid/sd2
how creatures will react on you .. (what spells are casted, when etc)
more complex like bosses  - are usualy done by scriptdev2 (in core now)

core issues:
well all mehanics... spawning system / movement system / loot system etc....
spells that doesnt work (also players) (some of them can be fixed by sd2)
pvp system
etc....

Im sure more complex info you can find on cmangos wiki....
