### ISSUE TITLE
 Fix for Kirtons the Herold 

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#16]
This NPC is not attackable
 I don't know what the Flag 832 is 
 Fix is testet and Works fine

UPDATE creature_template SET UnitFlags='0' WHERE Entry='10506';

**Comment by Grz3s** [comment]
thanks for your report...
Unit Flags are set for purpose.. we can't just remove'em.
832 -  0x200(passive) 0x100(occ not attackable) 0x40(flag_unk_6)
-- now we need to find, when and why this flags was set... and what flags he has at respawn.
u can leave it with me ;)

**Comment by xfurry** [comment]
@Tauriella this is part of an event, so the flag has a purpose.
I'm not sure if the event is implemented in UDB, but maybe you can do some research on how it should work.

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=FkxkmDNnv3Y
https://github.com/Rushor/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/Scholomance/boss_kirtonos_the_herald.cpp

some flyaction after the npc is spawned by using the gameobject :)

**Comment by evil-at-wow** [comment]
Yes, the flag is there on purpose. You can't attack him initially. When placing the 'Blood of Innocents' item in the brazier as part of [a quest](http://www.wowhead.com/quest=5384/kirtonos-the-herald), you start a small event - you see the end of it in the movie linked by Rushor - in which Kirtonos flies into the porch and transforms, then becomes attackable/attacks. There is a text involved when he's summoned - `%s lets out a shrill cry.` - but I can't provide more sniffed data for the event, sadly.

**Comment by Tauriella** [comment]
@evil-at-wow 
The Flag 832 is wrong
Example with Flag 832:
You use the brazier with Blodd of... now the Boss Kirtonos spawned but you can't attack him
nothing happens

Example with Flag 0:
You use the brazier with Blodd of... now the Boss Kirtonos spawned and you can attack and the fight bigins.
Kirtonos  transformet after a while and give the TXT  %s lets out a shrill cry.

**Comment by xfurry** [comment]
> Yes, the flag is there on purpose. You can't attack him initially. When placing the 'Blood of Innocents' item in the brazier as part of a quest, you start a small event - you see the end of it in the movie linked by Rushor - in which Kirtonos flies into the porch and transforms, then becomes attackable/attacks. There is a text involved when he's summoned - %s lets out a shrill cry. - but I can't provide more sniffed data for the event, sadly.

I suppose this is enough to clarify things.
Will be implemented to UDB / SD2 soonish.

**Comment by evil-at-wow** [comment]
@Tauriella What I was trying to say is that the flags we use when Kirtonos spawns can be correct because 832 = 512 + 256 + 64 = UNIT_FLAG_PASSIVE + UNIT_FLAG_OOC_NOT_ATTACKABLE +UNIT_FLAG_UNK_6, so basically it says "he doesn't attack, nor can be attacked" (and then some other flag), which is actually correct behavior!
So unless you have sniffs to prove the flags are incorrect, I wouldn't change them.

But I do agree with you the encounter is not working properly, because currently he spawns with these flags and then nothing ever changes, which indeed means you'll never be able to attack him. What should happen is that the flags are removed again after the small intro event! And then you'll be able to attack him properly after the small event, and everything will work out fine!

Additional note to @xfurry: I have one screenshot of Kirtonos' corpse on my harddisk - sadly the only evidence I can find for this event - where I added a remark that he spawns as a bat, then after the flight transforms into an undead for the actual fight, but interestingly enough turns bat again when he dies (so the corpse is a bat).

**Comment by Grz3s** [comment]
- can't change his spawn point (handled by lock open in dbc)
- whole fight is handled by ACID script... so if anything is wrong there it need to be fixed there.
- apearing anim.. is unknown (need sniff) ..
sugested fix...pls check and let me know what u think..
``` SQL
-- Kirtonos the Herald
UPDATE creature_template SET MovementType = 2 WHERE entry = 10506;
DELETE FROM creature_movement_template WHERE entry = 10506;
INSERT INTO creature_movement_template (entry, point, position_x, position_y, position_z, waittime, script_id, orientation, model1, model2) VALUES
(10506,1,309.156,93.3245,101.662,0,0,3.17265,0,0),
(10506,2,299.559,93.255,105.634,10000,1050601,3.17972,0,0);
DELETE FROM dbscripts_on_creature_movement WHERE id = 1050601; 
INSERT INTO dbscripts_on_creature_movement (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(1050601,1,20,0,0,0,0,0,0,0,0,0,0,0,0,0,'movement chenged to 0:idle'),
(1050601,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0.1,''),
(1050601,3,22,233,0x01 | 0x10 | 0x20,0,0,0,0,0,0,0,0,0,0,0,'temp faction');
```

**Comment by Tauriella** [comment]
@Grz3s 
I have testet and yes it works perfect :)
Thank you
