### ISSUE TITLE
27347 - Corrosion Prevention

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#18]
This quest is buggy, "The zeppelin's fragmented power core should power the device. The one near the main crash works all the time, but the others flicker on and off"
Every power core fragment doesn't working

**Comment by Grz3s** [comment]
Thank you for report...
quest: 27347 - Added in patch 4.0.3
-----------
we talking about older ver. - q.11174
http://www.wowhead.com/quest=11174/deprecated-corrosion-prevention
Will check...and wi'll see what can be done...

**Comment by Dainara82** [comment]
yes  the oldone  sorry for the wrong ID

**Comment by Grz3s** [comment]
can you pls say what DB are u using? ....

**Comment by Grz3s** [comment]
this quest needs core help @xfurry @kvipka
-- https://www.youtube.com/watch?v=D5OylI4CdQY - pre cata
-- https://www.youtube.com/watch?v=baLRFcGvLfY 7:20 - cata
can watch both avis... quest didnt change due to cata release.
--------------------------------
we need 2 fix 2 parts:
let's focus on first one (main)
--------------------------------
23832 - Zeppelin Power Core (hidden npc - inside gameobject)
and he has an aura 42491 Energized Periodic
so:
```quote
ID - 42491 Energized Periodic
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 23 (SPELL_AURA_PERIODIC_TRIGGER_SPELL), value = 1, misc = 0 (0), miscB = 0, periodic = 2000
   Trigger spell (42492) Cast Energized. Chance = 101

-- 42492
Effect 0: Id 77 (SPELL_EFFECT_SCRIPT_EFFECT)
BasePoints = 42490
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
Radius (Id 23) 40,00
Effect 1: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 11174   -- quest id ???
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
Radius (Id 27) 50,00

-- 42490
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (22, 30) (TARGET_CASTER_COORDINATES, TARGET_ALL_FRIENDLY_UNITS_AROUND_CASTER)
Aura Id 4 (SPELL_AURA_DUMMY), value = 1, misc = 0 (0), miscB = 0, periodic = 0
Radius (Id 23) 40,00
```
My understanding of this (may be wrong...)
first:
npc 23832.. has aura 42491 Energized Periodic - that every 2secs.. trigger spell (42492)...
next:
42492 - has 2 effects:
this quest needs core help @xfurry @kvipka
-- https://www.youtube.com/watch?v=D5OylI4CdQY - pre cata
-- https://www.youtube.com/watch?v=baLRFcGvLfY 7:20 - cata
can watch both avis... quest didnt change due to cata release.
--------------------------------
we need 2 fix 2 parts:
let's focus on first one (main)
--------------------------------
23832 - Zeppelin Power Core (hidden npc - inside gameobject)
and he has an aura 42491 Energized Periodic
so:
```quote
ID - 42491 Energized Periodic
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 23 (SPELL_AURA_PERIODIC_TRIGGER_SPELL), value = 1, misc = 0 (0), miscB = 0, periodic = 2000
   Trigger spell (42492) Cast Energized. Chance = 101

-- 42492
Effect 0: Id 77 (SPELL_EFFECT_SCRIPT_EFFECT)
BasePoints = 42490
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
Radius (Id 23) 40,00
Effect 1: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 11174   -- quest id ???
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
Radius (Id 27) 50,00

-- 42490
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (22, 30) (TARGET_CASTER_COORDINATES, TARGET_ALL_FRIENDLY_UNITS_AROUND_CASTER)
Aura Id 4 (SPELL_AURA_DUMMY), value = 1, misc = 0 (0), miscB = 0, periodic = 0
Radius (Id 23) 40,00
```
My understanding of this (may be wrong...)
first
npc 23832 has aura 42491 Energized Periodic, that every 2secs trigger spell (42492).
next:
42492 - has 2 effects
1st casts 42490
2nd checks if player has quest 11174 on list. If yes, then spell 4290 is casted on player

You can see on cata avi... that before player takes this quest... objects have that blue Energized aura and stright after player accepts quest -- spell is casted on him
--------------------------------------------------------------------
So what doesnt work?
well... i gave aura 42491 to hidden npc ..and nothing happens,
aslo i checked (just for test spell 42490 and this spell works fine, lighting goes from npc to player).
So somewhere, (or in first or second spell) something breaks.

any ideas? ?:)

**Comment by xfurry** [comment]
Maybe this patch helps. I didn't test it very well, so I'm not sure if I'm missing something.

```diff
@@ -1548,10 +1548,18 @@ void Spell::EffectDummy(SpellEffectIndex eff_idx)
                     else
                         m_caster->CastSpell(m_caster, 42288, true);
 
                     return;
                 }
+                case 42489:                                 // Cast Ooze Zap When Energized
+                {
+                    if (!unitTarget)
+                        return;
+
+                    m_caster->CastSpell(unitTarget, m_spellInfo->CalculateSimpleValue(eff_idx), true);
+                    return;
+                }
                 case 42628:                                 // Fire Bomb (throw)
                 {
                     if (!unitTarget)
                         return;
 

```

**Comment by Dainara82** [comment]
what i have to do to use this patch? that i can test it

**Comment by xfurry** [comment]
@Dainara82 We are still working on this quest, so I wouldn't say that this is ready for testing.
Me and @Grz3s  were very busy in the last weeks and we didn't have a chance to work on it.

**Comment by Ulduar** [comment]
``` SQL
-- Script id: 42489
DELETE FROM dbscripts_on_spell WHERE id=42489;
INSERT INTO dbscripts_on_spell VALUES 
(42489,0,15,42490,0,0,0,8,0,0,0,0,0,0,0,0,'Cast Ooze Zap When Energized - Cast Triggered Energized!'),
(42489,1,15,42483,0,0,0,0,0,0,0,0,0,0,0,0,' Cast Ooze Zap When Energized Spell - Cast Ooze Channel on Target');
```
So easy is not it?

**Comment by xfurry** [comment]
> So easy is not it?

No, it's not this easy...
First we don't know if the logic of the spell is right. I think there are other things that we are missing, because there are missing spells and visuals involved.

Second, you dbscript patch doesn't replicate my core patch because of wrong data_flags. So let's _"give the core what belongs to the core"_...

**Comment by Grz3s** [comment]
Why noone "READS" what i said in first post....
nothing is missing there.... 
We have all spells....
also:
i can make this quest working ... but it not going to be right! 
- first: problem with 1st part (look above) i *can* force 23832 to cast that spell (42490)all the time ..... and it will work fine ...(it will cast lighting to player) -- so what is the problem there??
-- spell 42490 should be casted on *ANY* player on that area, only if player has quest 11174 taken. (u can see thet on avi)
u can see this on this spell:
```quote
Effect 0: Id 77 (SPELL_EFFECT_SCRIPT_EFFECT)
BasePoints = 42490
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
Radius (Id 23) 40,00
Effect 1: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 11174   -- quest id ??? <------- HERE
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
Radius (Id 27) 50,00
```

So im asking again... pls lets *focus* on this part...
only if this will be completed, then we can go to second part, where we can find another 3 spells:
42489
42483
42485 - q. credit

**Comment by Schmoozerd** [comment]
Oh, This is something i have never seen before. Very interesting!

**Comment by xfurry** [comment]
@Grz3s let's allocate some time and talk about this on IRC.
I'm pretty sure we can get it sorted out. I just need some time to go through all the details.

**Comment by xfurry** [comment]
Please try this one:

```diff
diff --git a/src/game/SpellEffects.cpp b/src/game/SpellEffects.cpp
index 490418b..da03f08 100644
--- a/src/game/SpellEffects.cpp
+++ b/src/game/SpellEffects.cpp
@@ -1550,6 +1550,26 @@ void Spell::EffectDummy(SpellEffectIndex eff_idx)
 
                     return;
                 }
+                case 42485:                                 // End of Ooze Channel
+                {
+                    if (!unitTarget || unitTarget->GetTypeId() != TYPEID_UNIT)
+                        return;
+
+                    unitTarget->CastSpell(m_caster, 42486, true);
+                    return;
+                }
+                case 42489:                                 // Cast Ooze Zap When Energized
+                {
+                    // only process first effect
+                    if (eff_idx != EFFECT_INDEX_0)
+                        return;
+
+                    if (!unitTarget || !m_caster->HasAura(m_spellInfo->CalculateSimpleValue(EFFECT_INDEX_1)))
+                        return;
+
+                    m_caster->CastSpell(unitTarget, m_spellInfo->CalculateSimpleValue(eff_idx), true);
+                    return;
+                }
                 case 42628:                                 // Fire Bomb (throw)
                 {
                     if (!unitTarget)
@@ -7658,6 +7678,18 @@ void Spell::EffectScriptEffect(SpellEffectIndex eff_idx)
                     unitTarget->CastSpell(unitTarget, 42291, true);
                     return;
                 }
+                case 42492:                                 // Cast Energized
+                {
+                    if (!unitTarget || unitTarget->GetTypeId() != TYPEID_PLAYER)
+                        return;
+
+                    uint32 questId = m_spellInfo->CalculateSimpleValue(EFFECT_INDEX_1);
+                    if (!questId || !GetQuestTemplateStore(questId) || !((Player*)unitTarget)->IsCurrentQuest(questId))
+                        return;
+
+                    m_caster->CastSpell(m_caster, m_spellInfo->CalculateSimpleValue(eff_idx), true);
+                    return;
+                }
                 case 42578:                                 // Cannon Blast
                 {
                     if (!unitTarget)
diff --git a/src/game/SpellMgr.cpp b/src/game/SpellMgr.cpp
index a7fcade..6143380 100644
--- a/src/game/SpellMgr.cpp
+++ b/src/game/SpellMgr.cpp
@@ -704,6 +704,7 @@ bool IsPositiveEffect(SpellEntry const* spellproto, SpellEffectIndex effIndex)
             switch (spellproto->Id)
             {
                 case 42436:                                 // Drink!
+                case 42492:                                 // Cast Energized
                 case 46650:                                 // Open Brutallus Back Door
                 case 62488:                                 // Activate Construct
                 case 64503:                                 // Water

```

**Comment by Grz3s** [comment]
no luck with this patch... nothing happens :(

**Comment by xfurry** [comment]
I tested my patch and it looked fine (at least for the first kill credit).
I will test again, based on the updated that you provided, but as per my understanding it should work fine.

There might be some small problems regarding the targets and channel spells, but the overall logic should be correct.

**Comment by Grz3s** [comment]
so u tested it...and ... our hidden in gameobject npc "Zeppelin Power Core" ... will be casting every 2 secs.. that blue lighting spell.... and if any player will come close enough (with quest 11174) then.. blue lighting will go to player also...
is that working fine for you?

**Comment by xfurry** [comment]
Yes, everything is working fine
The Zeppelin Power Core has the periodic aura, which turns into blue only when there is a player around that has the quest active, and channels the blue beam on the player.
The player channels the item spell only the Zeppelin power core is channeling the blue beam on the player, and the player gets the kill credit.

However there is a problem....
After I use the item on the npc and I get the first kill credit, everything stops working... I'm not sure on why is this happening, but the Zeppelin Power Core isn't able to find any target for the periodic spell anymore.
Funny enough, this won't work again unless I restart the server. So some further testing is required, that's why I would appreciate some feedback.

**Comment by xfurry** [comment]
@Grz3s I think I found the problem.
It seems that spell 42492 targets won't work after player gets in combat. 
Do you happen to know the faction of npc 23832? Maybe this is a problem.

```
Effect 0: Id 77 (SPELL_EFFECT_SCRIPT_EFFECT)
BasePoints = 42490
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
Radius (Id 23) 40.00

Effect 1: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 11174
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
Radius (Id 27) 50.00
```

Maybe poke @Schmoozerd about this.

**Comment by Grz3s** [comment]
hey @xfurry 
got some legit info:
```code
DELETE FROM `creature_template_addon` WHERE `entry` = 23832;
INSERT INTO `creature_template_addon` (`entry`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(23832, 0, 0x0, 0x0, '42491'), -- 23832
(23832, 0, 0x0, 0x0, '42490'), -- 23832 -- why this came on sniff ??

DELETE FROM `creature_template` WHERE `entry` = 23832;
INSERT INTO `creature_template` (`entry`, `gossip_menu_id`, `minlevel`, `maxlevel`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `BaseAttackTime`, `RangeAttackTime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `VehicleId`, `HoverHeight`) VALUES
(23832, 0, 1, 1, 35, 0, 1, 1.142857, 2000, 2000, 1, 0, 0, 0, 0, 1), -- 23832
```
that second addon .... can be here becouse it was sniffed during quest???
and faction looks ok = 35

**Comment by xfurry** [comment]
Spell 42490 is cast by 42492 when the player is target and it has quest 27347 active.
The entire logic is covered in my patch.
The only problem is when the player enters combat, spell 42492 won't fine the player as a (friendly) target. I'm not sure why is this, but I think the problem is around here: https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Spell.cpp#L1874

**Comment by Grz3s** [comment]
quest = 27347 - was added in 4.0.3
we talking about = 11174
anyway.... i have no idea why your patch doesnt work for me :(

**Comment by xfurry** [comment]
It doesn't matter which quest we are talking about because both have the same mechanics.
The quest id is added in the spell effect:

Before 4.x
```
Effect 1: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 11174
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
Radius (Id 27) 50.00
```

After 4.x
```
Effect 1: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 27347
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
Radius (Id 27) 50.00
```

**Comment by Grz3s** [comment]
```code
42492:
AttributesEx2: 0x00000004 (SPELL_ATTR_EX2_IGNORE_LOS)
AttributesEx3: 0x10000000 (SPELL_ATTR_EX3_UNK28)
AttributesEx4: 0x00002000 (SPELL_ATTR_EX4_UNK13)
```
maybe  these missing attr. making a problem here?

**Comment by Grz3s** [comment]
hey @xfurry good news...
try this one:
```code
-- Zeppelin Power Core -- update
UPDATE creature_template SET MovementType = 0, InhabitType = 4 WHERE entry = 23832;
UPDATE creature SET spawndist = 0, MovementType = 0 WHERE id = 23832;
DELETE FROM creature_addon WHERE guid BETWEEN 18582 and 18588;
DELETE FROM creature_template_addon WHERE entry = 23832;
-- Zeppelin Power Core
Delete from `creature_ai_scripts` where `id`= 2383201;
Insert into `creature_ai_scripts` values 
('2383201','23832','1','0','100','1','1000','1000','5000','5000','11','42491','0','6','0','0','0','0','0','0','0','0','Zeppelin Power Core - Cast Energized Periodic while OOC');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '23832';
```
and what do you think ? :)

**Comment by xfurry** [comment]
Why do you want to cast 42491 on OOC timer?
This aura doesn't expire, so you only need to cast it once, on spawn. Either by c_t_a or by eventAI, but the result should be the same.

**Comment by Grz3s** [comment]
yes ... but this ...fixes problem with
```quote
The only problem is when the player enters combat, spell 42492 won't fine the player as a (friendly) target. 
```
and you can simply finish this quest....

**Comment by Ulduar** [comment]
Maybe creature_template addon and NullAI, then the aura disappears and can not evade leave.
