### ISSUE TITLE
12778 - The Scarlet Apocalypse

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#19]
Can't interact with the Lich King couse  he stay in the Wall 
i used ".npc move" that he stay on the right position

**Comment by Grz3s** [comment]
DK zone is in "rebuilding progres" 
 So fix will come "soon" ;)

**Comment by Tauriella** [comment]
Tip:
relog and it works :(

**Comment by Grz3s** [comment]
This one .. is core problem (DB has correct for this creature)
Something with communication server <-->client
we need core devs to look at his...

**Comment by adellaci** [comment]
@Grz3s 
With the updates, has this been corrected?

**Comment by Grz3s** [comment]
unfortunately no...
you can see on forum ...no "core dev" was interested with this at all.

Problem is simple. (somehow objects are loaded by client faster than creatures that are spawned on top of them)...
I tried few things ... but im not that good with core.. (so had no success)
I should close issue here, because problem is on core side and its nothing to do with database.
Reason why its still keept like this... is I dont want it to be forgotten...

**Comment by Grz3s** [comment]
should be fixed
