### ISSUE TITLE
Quest 9644 and 

### ISSUE THREAD

**Issue by apo126** [unified-db/Database#221]
The quest 9644 "Nightbane": the Blackened Urn cannot be found or cannot be touched.

The quest 11064 "Dragonmaw Race: The Ballad of Oldie McOld": after the quest was taken, Murg "Oldie" Muckjaw did not move and nothing happened.

**Comment by xfurry** [comment]
poke @killerwife and @Grz3s for the right DB data for these quests.

I think that quest 11064 (and the other similar quests) can be done by escort, or some kind of DB conditions.

**Comment by killerwife** [comment]
1. nightbane - I dont have that one, but @Grz3s  might, since I saw it lying around somewhere
2. the races are all not scripted, and without a sniff will be nearly impossible, not to mention correct movement speed, but i didnt ask anyone about this sniff yet, because i didnt have time

**Comment by xfurry** [comment]
> the races are all not scripted, and without a sniff will be nearly impossible

There are some videos. We can figure it out. It doesn't have to be copy 100% blizz, approximations are accepted when we don't have full documentation.
I just want to make sure that the spawns requires for the quests, as well as unit flags are fine.

**Comment by killerwife** [comment]
The chest is a bit problematic because the history for it is a little hazy. The trouble is, and some of this are only assumptions:
1. it changed in wotlk, meaning it worked differently, from what i can tell, the urn was spawned on the ground, and the item was 100% no longer needed
2. in TBC however, it looks like at some point the urn was placed on the ground (not sure about this), and the quest gave a urn item (100% sure about this one) which could be used for summoning. There is also a SPELL_FOCUS GO in the area in TBC (unsure on wotlk, since in wotlk it could very well be done only through the urn on the ground) for the summon nightbane spell. What i dont know at all, is that whether the quest Nightbane gave a temporary summon nightbane item for usage during quest or if the urn on the ground was used.

**Comment by killerwife** [comment]
About the races, I did them back in the day on retail and without exact WPs and speeds of mobs it cannot be recreated the way it was because the encounters were super fine tuned, just the way some "knockback" spells are, for which i had to use analytical math equation to make it work properly. (darkmoon faire cannon)

**Comment by Grz3s** [comment]
quest 9644 "Nightbane":  - fixed
quest 11064 "Dragonmaw Race: The Ballad of Oldie McOld":   reported there: https://github.com/cmangos/wotlk-db/issues/167  -- we'll keep only one open
